
export const authConstant = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
}

export const userConstant = {
    CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    CREATE_USER_FAILURE: "CREATE_USER_FAILURE",
    GET_USER_REQUEST: "GET_USER_REQUEST",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_FAILURE: "GET_USER_FAILURE",
    UPDATE_STATUS_USER_REQUEST: "UPDATE_STATUS_USER_REQUEST",
    UPDATE_STATUS_USER_SUCCESS: "UPDATE_STATUS_USER_SUCCESS",
    UPDATE_STATUS_USER_FAILURE: "UPDATE_STATUS_USER_FAILURE"
}

export const fundManagement = {
    FETCH_USER_DATA_REQUEST: "FETCH_USER_DATA_REQUEST",
    FETCH_USER_DATA_SUCCESS: "FETCH_USER_DATA_SUCCESS",
    FETCH_USER_DATA_FAILURE: "FETCH_USER_DATA_FAILURE",
    ADD_FUND_BY_ADMIN_REQUEST: "ADD_FUND_BY_ADMIN_REQUEST",
    ADD_FUND_BY_ADMIN_SUCCESS: "ADD_FUND_BY_ADMIN_SUCCESS",
    ADD_FUND_BY_ADMIN_FAILURE: "ADD_FUND_BY_ADMIN_FAILURE",
    DEDECT_FUND_BY_ADMIN_REQUEST: "DEDECT_FUND_BY_ADMIN_REQUEST",
    DEDECT_FUND_BY_ADMIN_SUCCESS: "DEDECT_FUND_BY_ADMIN_SUCCESS",
    DEDECT_FUND_BY_ADMIN_FAILURE: "DEDECT_FUND_BY_ADMIN_FAILURE",
    GET_ALL_RETAILER_DATA_REQUEST: "GET_ALL_RETAILER_DATA_REQUEST",
    GET_ALL_RETAILER_DATA_SUCCESS: "GET_ALL_RETAILER_DATA_SUCCESS",
    GET_ALL_RETAILER_DATA_FAILURE: "GET_ALL_RETAILER_DATA_FAILURE",
    GET_ALL_DISTRIBUTOR_DATA_REQUEST: "GET_ALL_DISTRIBUTOR_DATA_REQUEST",
    GET_ALL_DISTRIBUTOR_DATA_SUCCESS: "GET_ALL_DISTRIBUTOR_DATA_SUCCESS",
    GET_ALL_DISTRIBUTOR_DATA_FAILURE: "GET_ALL_DISTRIBUTOR_DATA_FAILURE",
    FETCH_ALL_ROLES_SUMMARY_REQUEST: "FETCH_ALL_ROLES_SUMMARY_REQUEST",
    FETCH_ALL_ROLES_SUMMARY_SUCCESS: "FETCH_ALL_ROLES_SUMMARY_SUCCESS",
    FETCH_ALL_ROLES_SUMMARY_FAILURE: "FETCH_ALL_ROLES_SUMMARY_FAILURE"

}